name: طب‌نما - تجربیات حوزه سلامت
url: https://tebnama.github.io
baseurl: /
permalink: /:title/
paginate_path: /page/:num/
paginate: 200
disqus:
github: https://github.com/tebnama/tebnama.github.io/
reviewActionUrl: https://get-review-form.tebnama.workers.dev
google_analytics:
webmaster_verifications:
  google: 
defaults:
  - scope:
      path: assets/*
    values:
      sitemap: false 
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
plugins:
  - jekyll-sitemap
  - jekyll-feed 
  - jekyll-paginate
  - jekyll-seo-tag  
